spring.application.name=fundoo_notes
# Enable H2 console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Datasource configuration
spring.datasource.url=jdbc:h2:mem:fundoo_db
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA / Hibernate
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Artemis configuration
spring.artemis.mode=embedded

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

# Mail configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=sandeepchahar796@gmail.com
spring.mail.password=ljei hkmi qxtt vqsj
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true